# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BIzM42-PgW2-ez7okX5LCoonO2OE-049
"""



import pandas as pd

data = {'A': [12, 21, 35, 47, 52],
        'B': [6, 7, 8, 9, 10],
        'C': [11, 12, 13, 14, 15]}
df = pd.DataFrame(data)

mask = (df['A'] > 2) & (df['B'] < 9)


result = df[mask]

print(result)

import numpy as np

np.random.seed(0)
data = np.random.randn(100, 4)


mean_values = np.mean(data, axis=0)
median_values = np.median(data, axis=0)
std_deviation = np.std(data, axis=0)

print("Mean values:", mean_values)
print("Median values:", median_values)
print("Standard deviation:", std_deviation)


correlation_matrix = np.corrcoef(data, rowvar=False)

print("Correlation coefficient matrix:")
print(correlation_matrix)